### PR TITLE
security update

### PR DESCRIPTION
**Pull request by Azdaroth**

### CODE REVIEW

**Comment by Azdaroth** [comment]
Huh, this was supposed to update rack, what happened here :doge:

**Comment by thilonel** [comment]
@Azdaroth Did you use --source?

**Comment by Azdaroth** [comment]
@thilonel Lol, no, it's because  example/Gemfile.lock is causing issues, not the top-level Gemfile :D

**Comment by Azdaroth** [comment]
@thilonel Hmm, interesting, specs are failing for JRuby due to not being able to satisfy some dependency.

**Comment by thilonel** [comment]
Not very interesting. 😄 Do you want me to look into this myself? 😅

**Comment by Azdaroth** [comment]
> Not very interesting.

😂 

Well, seems like it indeed it got your attention, so feel free to check this out :trollface: One solution would be to drop the support for JRuby :P

**Comment by thilonel** [comment]
@Azdaroth dropping 😄 I couldn't even install bundle locally with JRuby with latest java... not spending another minute on this until we must.

**Comment by Azdaroth** [comment]
@thilonel Wanna do a release? :D

**Comment by thilonel** [comment]
Done: https://rubygems.org/gems/omniauth-bookingsync/versions/1.0.0

**Pull request merged**
